import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./globals.css";

import NavBar from "./components/NavBar";
import Universe from "./components/Universe";

const inter = Source_Code_Pro({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={inter.className}> 
        <div className = "flex min-h-screen flex-col">
          <NavBar />
          <Universe />
          {children}
        </div>
      </body>
    </html>
  );
}
